INSERT INTO `products` (`id`, `name`, `code`, `price`,'image') VALUES
(1.,'Veg Manchurian','VM',40.00,'product-images/vegmanchurian.jpg'),
(2.,'Paneer Manchurian','PM',60.00, 'product-images/paneermanchurian.jpg'),
(3.,'Chicken 65','C65',80.00, 'product-images/chicken65.jpg'),
(4.,'Chicken Manchurian', 'CM', 60.00, 'product-images/chickenmanchurian.jpg'),
(5.,'Veg Noodles','VN',40.00, 'product-images/vegnoodles.jpg'),
(6.,'Egg Noodles','EN',45.00, 'product-images/eggnoodles.jpg'),
(7.,'Double Egg Noodles','DEN',50.00, 'product-images/doubleegg.jpg'),
(8.,'Veg Manchurian Noodles','VMN',50.00, 'product-images/vegmannoodles.jpg'),
(9.,'Chicken Noodles','CN',50.00, 'product-images/chickennoodles.jpg'),
(10.,'Veg Fried Rice','VFR',40.00, 'product-images/vegfriedrice.jpg'),
(11.,'Egg Fried Rice','EFR',45.00, 'product-images/eggfriedrice.jpg'),
(12.,'Chicken Fried Rice','CFR',50.00, 'product-images/chickenfriedrice.jpg'),
(13.,'Jeera Rice','JR',50.00, 'product-images/jeerarice.jpg'),
(14.,'Meals','M',60.00, 'product-images/meal.jpg'),
(15.,'Chicken Biryani','CB',120.00, 'product-images/chickenbiryani.jpg'),
(16.,'Sambar','S',20.00, 'product-images/sambar.jpg'),
(17.,'Dal','D',20.00, 'product-images/dal.jpg'),
(18.,'Veg Curry','VC',20.00, 'product-images/vegcurry.jpg'),
(19.,'Curd','C',20.00, 'product-images/curd.jpg'),
(20.,'White Rice','WR',30.00, 'product-images/rice.jpg'),
(21.,'Chapathi(2 Nos) with curry','CC',30.00, 'product-images/chapati.jpg'),
(22.,'Parota(2Nos) with curry','PC',30.00, 'product-images/parota.jpg'),
(23.,'Idli(3 Nos)','BI',20.00, 'product-images/idli.jpg'),
(24.,'Plain Dosa','BPD',25.00, 'product-images/plaindosa.jpg'),
(25.,'Onion Dosa','BOD',30.00, 'product-images/oniondosa.jpg'),
(26.,'Masala Dosa','BMD',30.00, 'product-images/masaladosa.jpg'),
(27.,'Egg Dosa','BED',40.00, 'product-images/eggdosa.jpg'),
(28.,'Upma Dosa','BUD',40.00, 'product-images/upmadosa.jpg'),
(29.,'Tea','TEA','07.00', 'product-images/tea.jpg');
